apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calculadora
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/crisz-source/manifestos'
    targetRevision: HEAD
    path: manifests/calculadora
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
