name: CI - testando

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }} 
  MANIFEST_REPO: crisz-source/manifestos

jobs:
  update-tomcat:
    runs-on: ubuntu-latest
    env: 
      APP_NAME: tomcat
      APP_PATH: manifests/tomcat/tomcat.yaml
    steps:
      - name: Clonar repositório de manifests 
        uses: actions/checkout@v3
        with:
          repository: ${{ env.MANIFEST_REPO }}
          token: ${{ secrets.MANIFEST_REPO_TOKEN }}
          path: manifests

      - name: Definir próxima versão do Tomcat
        id: version
        run: |
          cd manifests
          CURRENT=$(grep "image:" $APP_PATH | sed 's/.*tomcat://')
          if [[ -z "$CURRENT" ]]; then
            NEW_TAG="9.0"
          else
            MAJOR=$(echo $CURRENT | cut -d. -f1)
            MINOR=$(echo $CURRENT | cut -d. -f2)
            NEW_TAG="$MAJOR.$((MINOR+1))"
          fi
          echo "new_tag=$NEW_TAG" >> $GITHUB_OUTPUT

      - name: Atualizar tag no manifesto do Tomcat
        run: |
          cd manifests
          sed -i "s|image:.*tomcat:.*|image: tomcat:${{ steps.version.outputs.new_tag }}|" $APP_PATH

      - name: Commit e push
        run: |
          cd manifests
          git config user.name "github-actions"
          git config user.email "ci@github.com"
          git add $APP_PATH
          git commit -m "chore(tomcat): update tomcat image to version ${{ steps.version.outputs.new_tag }}"
          git push

  build-calculadora:
    needs: update-tomcat  # <-- Só executa depois que o Tomcat rodar
    runs-on: ubuntu-latest
    env:
      APP_NAME: calculadora
      IMAGE_NAME: calculadora-custom
      APP_PATH: manifests/calculadora/nginx-deployment.yaml
    steps:
      - name: Checkout código fonte
        uses: actions/checkout@v3

      # - name: Definir próxima tag de versão
      #   id: version
      #   run: |
      #     TIMESTAMP=$(date +%s)
      #     echo "new_tag=1.${TIMESTAMP}" >> $GITHUB_OUTPUT

      - name: Definir próxima tag incremental
        id: version
        run: |
          git fetch --tags
          LAST_TAG=$(git tag | sort -V | tail -n 1)
          if [[ -z "$LAST_TAG" ]]; then
            NEW_TAG="1.0"
          else
            MAJOR=$(echo $LAST_TAG | cut -d. -f1)
            MINOR=$(echo $LAST_TAG | cut -d. -f2)
            NEW_TAG="$MAJOR.$((MINOR+1))"
          fi
          echo "new_tag=$NEW_TAG" >> $GITHUB_OUTPUT

      - name: Login no DockerHub
        run: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - name: Build da imagem Docker
        run: docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME:${{ steps.version.outputs.new_tag }} ./apps/

      - name: Push da imagem para o DockerHub
        run: docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:${{ steps.version.outputs.new_tag }}

      - name: Clonar repositório de manifests
        uses: actions/checkout@v3
        with:
          repository: ${{ env.MANIFEST_REPO }}
          token: ${{ secrets.MANIFEST_REPO_TOKEN }}
          path: manifests

      - name: Atualizar tag no manifesto
        run: |
          cd manifests
          sed -i "s|image:.*|image: $DOCKERHUB_USERNAME/$IMAGE_NAME:${{ steps.version.outputs.new_tag }}|" $APP_PATH

      - name: Commit e push
        run: |
          cd manifests
          git config user.name "github-actions"
          git config user.email "ci@github.com"
          git add $APP_PATH
          git commit -m "chore(calculadora): update image tag to ${{ steps.version.outputs.new_tag }}"
          git push

  deploy:
      needs: [update-tomcat, build-calculadora] # <-- Só roda depois dos dois
      runs-on: ubuntu-latest
      steps:
        - name: Clonar repositório de manifests
          uses: actions/checkout@v3
          with:
            repository: ${{ env.MANIFEST_REPO }}
            token: ${{ secrets.MANIFEST_REPO_TOKEN }}
            path: manifests

        - name: Confirmar mudanças no repositório de manifests
          run: |
            cd manifests
            echo "### Alterações aplicadas no repositório de manifests ###"
            git log -2 --oneline
            git status
